name: build test library

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v2
    - name: Compilar test_library.c en Docker
      run: |
        docker run --rm -v "$(pwd)/library:/code" ubuntu:latest sh -c "apt-get update && apt-get install -y build-essential && cd /code && test_library.c -o game"
