name: Build

on: push

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up MSVC compiler
        uses: microsoft/setup-msvc@v1.6.2
        with:
          msvc-version: 'latest'

      - name: Build C++ program
        run: cl.exe /library/test_library.c /Fe"game.exe"
