name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build-essential
      run: sudo apt-get install -y build-essential
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..
    - name: Build
      run: |
        cd build
        make
    - name: Run tests
      run: |
        cd build
        make test
    - name: Create package
      run: |
        cd build
        make package
