name: CharDeveloping-Test-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install MinGW
        run: |
          choco install mingw -y
      - name: Build project
        run: |
          cd D:\a\charDeveloping\charDeveloping
          cmake .
          make
