name: CharDeveloping-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CharDeveloping/codeblocks-windows-build-action@v1
        with:
          path-to-cbp: 'CharDeveloping.cbp'
          build-target: 'Debug'
