name: CharDeveloping-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: List project directory
        run: dir
      - name: Set up CodeBlocks
        uses: GameServerManagers/WindowsGSM@main
      - name: Build project
        run: |
          mingw32-make.exe -f "ruta/al/proyecto/Makefile" BUILD_TARGET=debug PROJECT_LOGO=1 PROJECT_NAME=CharDeveloping
