name: Slack Notification

on:
  push:
    branches:
      - main

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2.1.1
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          args: |
            {
              "attachments": [
                {
                  "fallback": "Push event detected on ${{ github.repository }}",
                  "color": "#36a64f",
                  "pretext": "Push event detected on ${{ github.repository }}",
                  "author_name": "${{ github.actor }}",
                  "title": "${{ github.ref }}",
                  "title_link": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}",
                  "text": "Commit message: ${{ github.event.head_commit.message }}",
                  "footer": "GitHub Actions",
                  "footer_icon": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
                }
              ]
            }
